Django/recipebook-mangabat-aster/ledger/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView, RecipeCreateView, recipe_list, RecipeAddImageView

urlpatterns = [
    path('recipes/list', recipe_list, name="list"),
    path('recipe/<int:pk>', RecipeDetailView.as_view(), name="recipe"),
    path('recipe/add', RecipeCreateView.as_view(), name="create"),
    path('recipe/<int:pk>/add_image',
         RecipeAddImageView.as_view(), name="add_image")
]

app_name = 'ledger'

Django/recipebook-mangabat-aster/recipebook/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledger.urls', namespace='ledger')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/recipebook-mangabat-aster/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator


class Profile (models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.TextField(validators=[MinLengthValidator(
        255, 'the field must contain at least 255 characters')])

    def __str__(self):
        return self.name

Django/recipebook-mangabat-aster/ledger/models.py
from django.db import models
from django.urls import reverse

from accounts.models import Profile
# Create your models here.


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ledger:ingredient', args=[self.pk])


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    author = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ledger:recipe', args=[self.pk])


class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=50)
    ingredient = models.ForeignKey(
        'Ingredient',
        on_delete=models.CASCADE,
        related_name="recipe"
    )
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        related_name="ingredients"
    )


class RecipeImage(models.Model):
    image = models.ImageField(upload_to="images/", null=False)
    description = models.TextField(max_length=255)
    recipe = models.ForeignKey(
        'Recipe',
        on_delete=models.CASCADE,
        related_name="images"
    )

Django/recipebook-mangabat-aster/ledger/forms.py
from django import forms

from .models import Recipe, RecipeImage


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'


class ImageForm(forms.ModelForm):
    class Meta:
        model = RecipeImage
        exclude = ['recipe']

Django/recipebook-mangabat-aster/accounts/views.py
from django.shortcuts import render

# Create your views here.

Django/recipebook-mangabat-aster/ledger/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse
# Create your views here.

from .models import Recipe, RecipeIngredient, RecipeImage
from .forms import RecipeForm, ImageForm


def recipe_list(request):
    recipes = Recipe.objects.all()
    form = RecipeForm()
    if request.method == "POST":
        form = RecipeForm(request.POST)
        if form.is_valid:
            recipe = Recipe()
            recipe.name = recipe.cleaned_data.get('name')
            recipe.author = recipe.cleaned_data.get('author')
            recipe.save()

            form.save()
    ctx = {
        "recipes": recipes,
        "recipeingredients": RecipeIngredient.objects.all(),

    }
    return render(request, 'recipe_list.html', ctx)


def page(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    ctx = {"recipe": recipe}
    return render(request, 'page.html', ctx)


class RecipeListView(ListView):
    model = Recipe
    template_name = 'recipe_list.html'


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'page.html'


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = 'recipe_create.html'
    form_class = RecipeForm


class RecipeAddImageView(LoginRequiredMixin, CreateView):
    model = RecipeImage
    template_name = 'add_image.html'
    form_class = ImageForm

    def get_success_url(self):
        return reverse_lazy('ledger:recipe', kwargs={'pk': self.object.recipe.pk})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['recipe_pk'] = self.kwargs['pk']
        return ctx

    def form_valid(self, form):
        form.instance.recipe = Recipe.objects.get(pk=self.kwargs["pk"])
        return super().form_valid(form)

Django/recipebook-mangabat-aster/templates/add_image.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Add Recipe Image{% endblock %}
{% block page_title %}Add Recipe Image{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button>Submit</button>
</form>
<a href="{% url 'ledger:recipe' recipe_pk %}">Cancel</a>
{% endblock %}

Django/recipebook-mangabat-aster/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <style>
            #login{
                display:none;
            }
        </style>
        {% block styles %}{% endblock %}
    </head>
    <body>
        <div id="content">
            <header>
                <h1>Recipe Book</h1>
                <h2>You are viewing: {% block page_title %}{% endblock %}</h2>
            </header>
            <div id="{% block page_type %}{% endblock %}">
                {% if request.user.is_authenticated %}
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit">Log Out</button>
                    </form>
                {% else %}
                    <a href="{% url 'login' %}">Log In</a>
                {% endif %}
            </div>    
            {% block content %}{% endblock %}
        </div>
        {% block scripts %}{% endblock %}
    </body>
</html>

Django/recipebook-mangabat-aster/templates/page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Recipe{% endblock %}
{% block page_title %}Recipe Details{% endblock %}
{% block styles %}
<style>
    img{
        max-width: 500px;
        max-height: 500px;
        padding: 2;
    }
</style>
{% endblock %}
{% block content %}
<ul>
    <h2>{{ recipe.name }}</h2>
    {% for picture in recipe.images.all %}
        <img src="{{ picture.image.url }}" alt="{{ picture.description }}">
        {% empty %}
            <p>No images uploaded</p>
    {% endfor %}
    {% for ingredient in recipe.ingredients.all %}
        <li>{{ ingredient.ingredient.name }} - {{ ingredient.quantity }}</li>
    {% endfor %}
    <p>Recipe by: {{ recipe.author }}</p>
    <a href="{% url 'ledger:add_image' recipe.pk %}">Add Image</a>
    <br>
    <a href="/recipes/list">Recipe List</a>
</ul>
{% endblock %}

Django/recipebook-mangabat-aster/templates/recipe_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Recipe Creation{% endblock %}
{% block page_title %}Recipe Creation Page{% endblock %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button>Submit</button>
</form>
<a href="/recipes/list">Recipe List</a>
{% endblock %}

Django/recipebook-mangabat-aster/templates/recipe_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Recipe Book{% endblock %}
{% block page_title %}Recipe List{% endblock %}
{% block content %}
<form action=""></form>
<ul>
    {% for recipes in recipes %}
    <li>
        <a href="{{recipes.get_absolute_url}}">
            {{recipes}}
        </a>
    </li>
    {% endfor %}
</ul>
<a href="/recipe/add">Create a new recipe!</a>
{% endblock %}