Django/hobbysite-E-5-main/commissions/urls.py
from django.urls import path

from .views import CommissionListView, CommissionDetailView, CommissionCreateView, JobCreateView, CommissionUpdateView, JobUpdateView, JobApplicationUpdateView


urlpatterns = [
    path('list', CommissionListView.as_view(), name="list"),
    path('detail/<int:pk>', CommissionDetailView.as_view(),
         name="commission_detail"),
    path('add', CommissionCreateView.as_view(), name="add"),
    path('detail/<int:pk>/add', JobCreateView.as_view(), name="add_job"),
    path('<int:pk>/edit', CommissionUpdateView.as_view(), name="update"),
    path('jobs/<int:pk>/edit/', JobUpdateView.as_view(), name="update_job"),
    path('commissions/<int:commission_pk>/jobs/<int:job_pk>/applications/<int:pk>/update/',
         JobApplicationUpdateView.as_view(), name="update_job_application"),

]

app_name = 'commissions'

Django/hobbysite-E-5-main/forum/urls.py
from django.urls import path

from .views import ThreadListView, ThreadDetailView, ThreadCreateView, ThreadUpdateView

urlpatterns = [
    path('threads', ThreadListView.as_view(), name='threads'),
    path('thread/<int:pk>', ThreadDetailView.as_view(), name='thread'),
    path('thread/add', ThreadCreateView.as_view(), name='add_thread'),
    path('thread/<int:pk>/edit', ThreadUpdateView.as_view(), name='edit_thread')
]

app_name = 'forum'

Django/hobbysite-E-5-main/hobbysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import HomePageView, DashboardView
from user_management.views import ProfileUpdateView


urlpatterns = [
    path('home/', HomePageView.as_view(), name='home'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls', namespace='forum')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
    path('profile', ProfileUpdateView.as_view(), name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('user_management.urls', namespace='user_management')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/hobbysite-E-5-main/merchstore/urls.py
from django.urls import path

from .views import MerchListView, MerchDetailView, MerchCreateView, MerchUpdateView, CartView, TransactionListView


urlpatterns = [
    path('items', MerchListView.as_view(), name='merch_list'),
    path('item/<int:pk>', MerchDetailView.as_view(), name='merch_detail'),
    path('item/add', MerchCreateView.as_view(), name='merch_create'),
    path('item/<int:pk>/edit', MerchUpdateView.as_view(), name='merch_update'),
    path('cart', CartView.as_view(), name='cart'),
    path('transactions', TransactionListView.as_view(), name='transaction_list'),
]

app_name = 'merchstore'

Django/hobbysite-E-5-main/user_management/urls.py
from django.contrib import admin
from django.urls import path

from .views import UserLoginView, UserLogoutView, UserCreateView


urlpatterns = [
    path('login_user/', UserLoginView.as_view(), name='login-user'),
    path('logout_user/', UserLogoutView.as_view(), name='logout-user'),
    path('register_user/', UserCreateView.as_view(), name='register-user'),
]

app_name = 'user_management'

Django/hobbysite-E-5-main/wiki/urls.py
from django.urls import path

from .views import WikiListView, WikiDetailView, WikiCreateView, WikiUpdateView


urlpatterns = [
    path('articles/', WikiListView.as_view(), name ='wiki_list'),
    path('article/<int:pk>', WikiDetailView.as_view(), name ='wiki_detail'),
    path('article/add/', WikiCreateView.as_view(), name ='wiki_create'),
    path('article/<int:pk>/edit/', WikiUpdateView.as_view(), name ='wiki_update'),
]

app_name = 'wiki'

Django/hobbysite-E-5-main/wiki/models.py
from django.db import models
from django.urls import reverse

from user_management.models import Profile


class ArticleCategory(models.Model):
    class Category(models.TextChoices):
        LAPTOPS = 'LAPTOPS'
        PHONES = 'PHONES'
        PROCESSORS = 'PROCESSORS'
        KEYBOARDS = 'KEYBOARDS'
        TELEVISIONS = 'TELEVISIONS'

    name = models.CharField(
        max_length=255, choices=Category.choices, default='TV')
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Article Categories'


class Article(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Profile,
        null=True,
        on_delete=models.SET_NULL,
        related_name='article_author',
    )
    category = models.ForeignKey(
        'ArticleCategory',
        null=True,
        on_delete=models.SET_NULL,
        related_name='categories',
    )
    entry = models.TextField()
    header_image = models.ImageField(
        upload_to="images/",
        null=True,
        blank=True,
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('wiki:wiki_detail', args=[self.pk])

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_on']


class Comment(models.Model):
    author = models.ForeignKey(
        Profile,
        null=True,
        on_delete=models.SET_NULL,
        related_name='wiki_author',
    )
    article = models.ForeignKey(
        'Article',
        null=True,
        on_delete=models.CASCADE,
        related_name='article',
    )
    entry = models.TextField(default='')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_on']

Django/hobbysite-E-5-main/wiki/forms.py
from django import forms

from .models import Article, Comment

class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category', 'entry', 'header_image']


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'category', 'entry', 'header_image']


class CommentForm(forms.ModelForm):
    entry = forms.CharField(widget=forms.Textarea, label="Comment")
    class Meta:
        model = Comment
        fields = ['entry']

Django/hobbysite-E-5-main/wiki/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, ModelFormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse

from .models import Article, ArticleCategory, Profile, Comment
from .forms import ArticleCreateForm, ArticleUpdateForm, CommentForm

import random


class WikiListView(ListView):
    model = Article
    template_name = 'wiki_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        
        laptop_articles = Article.objects.filter(category=ArticleCategory.objects.get(name='LAPTOPS'))
        phone_articles = Article.objects.filter(category=ArticleCategory.objects.get(name='PHONES'))
        processor_articles = Article.objects.filter(category=ArticleCategory.objects.get(name='PROCESSORS'))
        keyboard_articles = Article.objects.filter(category=ArticleCategory.objects.get(name='KEYBOARDS'))
        tv_articles = Article.objects.filter(category=ArticleCategory.objects.get(name='TELEVISIONS'))

        if current_user.is_authenticated:
            context['user_articles'] = Article.objects.filter(author=Profile.objects.get(user=current_user))
            context['laptop_articles'] = laptop_articles.exclude(author=Profile.objects.get(user=current_user))
            context['phone_articles'] = phone_articles.exclude(author=Profile.objects.get(user=current_user))
            context['processor_articles'] = processor_articles.exclude(author=Profile.objects.get(user=current_user))
            context['keyboard_articles'] = keyboard_articles.exclude(author=Profile.objects.get(user=current_user))
            context['tv_articles'] = tv_articles.exclude(author=Profile.objects.get(user=current_user))
        else:
            context['laptop_articles'] = laptop_articles
            context['phone_articles'] = phone_articles
            context['processor_articles'] = processor_articles
            context['keyboard_articles'] = keyboard_articles
            context['tv_articles'] = tv_articles

        return context
class WikiDetailView(ModelFormMixin, DetailView):
    model = Article
    form_class = CommentForm
    template_name = 'wiki.html'

    def get_success_url(self):
        return reverse('wiki:wiki_detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_article = Article.objects.get(pk=self.kwargs['pk'])
        current_category = current_article.category
        other_articles = Article.objects.exclude(pk=self.kwargs['pk']).filter(category=current_category)
        read_others = random.sample(list(other_articles), 2)
        article_image = current_article.header_image
        comments = Comment.objects.filter(article=current_article)
        
        context['current_article'] = current_article
        context['current_category'] = current_category
        context['other_articles'] = other_articles
        context['read_others'] = read_others
        context['article_image'] = article_image
        context['form'] = CommentForm()
        context['comments'] = reversed(comments)

        return context
    
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        print(form)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def form_valid(self, form):
        Comment.objects.create(entry=form.cleaned_data['entry'], author=Profile.objects.get(user=self.request.user), article=Article.objects.get(pk=self.kwargs['pk']))
        return super().form_valid(form)
    

class WikiCreateView(LoginRequiredMixin, CreateView):
    model = Article
    form_class = ArticleCreateForm
    template_name = 'wiki_create.html'

    def form_valid(self, form):
        form.instance.author = Profile.objects.get(user=self.request.user)
        return super().form_valid(form)
    

class WikiUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleUpdateForm
    template_name = 'wiki_create.html'

    def form_valid(self, form):
        form.instance.author = Profile.objects.get(user=self.request.user)
        return super().form_valid(form)
    
    def dispatch(self, request, *args, **kwargs):
        handler = super().dispatch(request, *args, **kwargs)
        user_profile = self.request.user.profile
        article = self.get_object()
        if not (article.author == user_profile):
            raise PermissionDenied
        return handler

Django/hobbysite-E-5-main/templates/commission_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Create Commission{% endblock %}

{% block styles %}
    <style>
        a{
            text-decoration: none;
            color:black;
        }
    </style>
{% endblock styles %}

{% block comm %}active{% endblock %}

{% block content %}
<h1>Create Commission</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <h2>JOBS</h2>
    {{ jobs.management_form }}
    <table>
        {% for form in jobs %}
            {{ form.as_table }}
        {% endfor %}
    </table>
    <button>Create</button>
</form>
<a href="/commissions/list">Cancel</a>
{% endblock content %}

Django/hobbysite-E-5-main/templates/commission_detail.html
{% extends './base.html' %}

{% load static %}

{% block title %}Commission Details{% endblock %}

{% block styles %}
    <style>

        #no_jobs{
            list-style-type: none;
        }
    </style>
{% endblock styles %}

{% block comm %}active{% endblock %}

{% block content %}
    <div id="header">
        <h2>{{ commission }}</h2>
        <p>{{ commission.description }}</p>
        <p><strong>Status:</strong> {{ commission.get_commission_status }}</p>
        <!-- <p>Created By: {{ commission.author.display_name }}</p> -->
    </div>
    <div id="job_list">
        {% if commission.jobs.all.exists %}
                {% for jobs in commission.jobs.all %}
                    <ul class="list-group position-relative start-50 top-50 bottom-50 translate-middle-x body" style="width:90vw; padding: 0.5vh;">        
                        <li class="list-group-item">
                            {{ jobs.role }}
                            {% for info in jobs_data %}
                                {% if info.job.role == jobs.role %}
                                    <p>Manpower Required: {{info.remaining_manpower}}</p>
                                    <p>Current Status: {{jobs.job_status}}</p>
                                    {% if commission.author != request.user.profile %}
                                        {% if jobs not in applied_jobs and info.remaining_manpower > 0 %} 
                                            <form method="POST" action="{% url 'commissions:commission_detail' commission.pk %}"> 
                                                {% csrf_token %}
                                                <input type="hidden" name="job_role" value="{{ jobs.role }}">
                                                <button type="submit" class="btn btn-primary btn-lg">Apply to Job</button>
                                            </form>
                                        {% else %}
                                            <form method="POST" action="{% url 'commissions:commission_detail' commission.pk %}"> 
                                                {% csrf_token %}
                                                <input type="hidden" name="job_role" value="{{ jobs.role }}">
                                                <button type="submit" class="btn btn-lg btn-primary" disabled>Cannot Apply</button>
                                            </form>
                                        {% endif %}
                                    {% else %}
                                        <a href="{% url 'commissions:update_job' jobs.pk %}"><button type="button" class="btn btn-outline-secondary btn-sm">Edit Job</button></a>
                                        {% for applicant in jobs.applications.all %}
                                            <p>
                                                {{applicant.applicant.display_name}} - {{ applicant.get_application_status }} <a href="{% url 'commissions:update_job_application' commission.pk jobs.pk applicant.pk %}"><button type="button" class="btn btn-outline-primary">Manage Applicant</button></a>
                                            </p>
                                        {% endfor %}
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </li>
                    </ul>
                {% endfor %}
            {% else %}
                <li id="no_jobs">No Jobs</li>
        {% endif %}
        <br>
        {% if commission.author == request.user.profile %}
            <div class="btn-group position-relative start-50 top-50 bottom-50 translate-middle-x" role="group">
                <!-- <button type="button" class="btn btn-outline-primary" href="{% url 'commissions:update' commission.pk %}">Update Commission</button>
                <button type="button" class="btn btn-outline-primary" href="{% url 'commissions:add_job' commission.pk %}">Add Job</button> -->
                
                <a href="{% url 'commissions:add_job' commission.pk %}" style="padding:1vw;"><button type="button" class="btn btn-outline-primary">Add Job</button></a>
                <a href="{% url 'commissions:update' commission.pk %}" style="padding:1vw;"><button type="button" class="btn btn-outline-primary">Update Commission</button></a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

Django/hobbysite-E-5-main/templates/forum_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Forum Details{% endblock %}

{% block styles %}
    <style>
        #content {
            position: relative;
            border: 1px solid black;
            border-radius: 5px;
            box-shadow: 2px 2px #888888;
            width: 70%;
            margin-top: 50px;
            margin-left: auto;
            margin-right: auto;
            word-wrap: break-word;
        }

        #return {
            position: absolute;
            top: -30px;
            color: black;
            text-decoration: none;
        }

        #return:hover {
            opacity: 0.7;
            transition: opacity 0.3s ease;
        }

        #edit_thread {
            position: absolute;
            right:0px;
            top: -30px;
            color: black;
            text-decoration: none;
        }

        #edit_thread:hover {
            opacity: 0.7;
            transition: opacity 0.3s ease;
        }

        #container {
            margin-left: auto;
            margin-right: auto;
            width: 70%;
            margin-bottom: 30px;
        }

        #container_title {
            border-bottom: 1px solid black;
            padding-left: 10px;
            padding-bottom: 2px;
            font-weight: bold;
            margin-top: 15px;
        }

        #comments_list {
            margin-bottom: 15px;
            text-align: left;
            padding-left: 10px;
            padding-right: 10px;
            list-style-type: none;
            text-decoration: none;
        }

        #comments_list li {
            word-wrap: break-word;
        }

        #content_list {
            border: 1px solid black;
            border-radius: 5px;
            box-shadow: 2px 2px #888888;
            margin-bottom: -5px;
            text-align: left;
            padding-left: 10px;
            list-style-type: none;
            text-decoration: none;
        }

        #content_link {
            cursor: pointer;
        }

        #content_list:hover {
            background-color: #F2F4F5;
            transition: background-color 0.2s ease;
        }

        #content_list li {
            word-wrap: break-word;
        }

        #comments_form {
            width: 70%;
            margin: 30px auto;
        }

        #comments_form button {
            cursor: pointer;
            opacity: 0.9;
            position: absolute;
            right: -5px;
            border: 1px solid black;
            border-radius: 2spx;
            box-shadow: 2px 2px #888888;
        }

        #comments_form button:hover {
            opacity: 0.7;
            box-shadow: 1px 1px #888888;
            transition: transform .2s ease-out;
        }

        #comments_form .add_comment {
            position: relative;
        }

        #comments_form p {
            margin-bottom: 0px;
        }

        textarea {
            resize: none;
            width: 100%;
        }
    </style>
{% endblock styles %}

{% block forum %}active{% endblock %}

{% block content %}
    <div id="content">
        <a id="return" href="{% url 'forum:threads'%}">Back to Forums</a>

        {% if is_owner %}
            <a id="edit_thread" href="{% url 'forum:edit_thread' pk=thread.pk %}">Edit Thread</a>
        {% endif %} 

        <p style="text-align: justify; width: 95%; margin: 10px auto; font-size: small;">Posted By: <span style="font-weight: bold;">{{ thread.author }}</span> | Category: {{ thread.category }}</p>
        <h3 style="text-align: center; width: 95%; margin: 15px auto">{{ thread.title }}</h3> 
        
        {% if thread.image %}
            <img src="{{ thread.image.url }}" style="position: relative; width: 35%; max-height: 35%;  display: block; margin-left: auto; margin-right: auto;">
        {% endif %} 

        <p style="text-align: justify; width: 95%; margin: auto;">{{ thread.entry }}</p>
        <br>
        <p style="text-align: justify; width: 95%; margin: auto; font-size: small;">Created On: {{ thread.created_on }}</p>
        <p style="text-align: justify; width: 95%; margin: auto; font-size: small;">Updated On: {{ thread.updated_on }}</p>
        <br>
    </div>

    <div id="container">
        <div id="container_title">
            Comments
        </div>

        {% for comment in comments %}
            <ul id="comments_list">
                <li>
                    <p style="font-weight: bold; font-size: small;">{{ comment.author }} <span style="font-weight: normal;">• {{ comment.updated_on }}</span></p> 
                    <p>{{ comment.entry }}</p>
                </li>
            </ul>
        {% endfor %}

        {% if comments|length == 0 %}
                <p class="posts" style="text-align: center;">No Comments To Show</p>
        {% endif %} 
        
        {% if request.user.is_authenticated %}
            <form id="comments_form" method="POST">
                <div class="add_comment">
                    <p>Add a comment</p>
                    {% csrf_token %}
                    {{ comments_form.entry }}
                    <button>Comment</button>
                </div>
            </form>
        {% endif %} 

        <div id="container_title">
            More Threads
        </div>

        {% for thread in more_threads %}
            <div id="content_link" onclick="location.href='{{ thread.get_absolute_url }}'">
                <ul id="content_list">
                    <li>
                        <p class="posts">{{ thread.title }}</p>
                    </li>
                </ul>
            </div>
        {% endfor %}

        {% if more_threads|length == 0 %}
            <p class="posts" style="text-align: center;">No Threads To Show</p>
        {% endif %} 
    </div>
{% endblock content %}

Django/hobbysite-E-5-main/templates/forum_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Forum List{% endblock %}

{% block styles %}
    <style>
        #content_list{
            border: 1px solid black;
            border-radius: 5px;
            box-shadow: 2px 2px #888888;
            margin-bottom: -5px;
            text-align: left;
            padding-left: 10px;
            list-style-type: none;
            text-decoration: none;
        }

        #content_link{
            cursor: pointer;
        }

        #content_list:hover{
            background-color: #F2F4F5;
            transition: background-color 0.2s ease;
        }

        #content_list li {
            word-wrap: break-word;
        }

        #category_container {
            margin-left: auto;
            margin-right: auto;
            width: 70%;
            margin-bottom: 30px;
        }

        #content_title {
            background-color: #70DCF8;
            border-top: 1px solid black;
            box-shadow: 3px 3px #888888;
            padding-left: 10px;
            padding-bottom: 2px;
            font-weight: bold;
        }

        .posts{
            color: black;
        }

        #user_content {
            display: flex;
            justify-content: space-between;
            background-color: #70DCF8;
            border-top: 1px solid black;
            box-shadow: 3px 3px #888888;
            padding-left: 10px;
            padding-right: 10px;
            padding-bottom: 2px;
            font-weight: bold;
        }

        #user_content *{
            margin: 0;
        }

        #add_thread {
            color: black;
            text-decoration: none;
            display: block;
            text-align: center;
        }

        #add_thread:hover{
            opacity: 0.7;
            transition: opacity 0.3s ease;
        }
    </style>
{% endblock styles %}

{% block forum %}active{% endblock %}

{% block content %}
    <h3 style="text-align: center;">Threads</h3> 
    {% if request.user.is_authenticated %}
        <div id="category_container">
            <div id="user_content">
                <p>User Threads</p>
                <a href="{% url 'forum:add_thread' %}" id="add_thread">Add Thread</a>
            </div>
        {% for post in user_threads %}
            <div id="content_link" onclick="location.href='{{ post.get_absolute_url }}'">
                <ul id="content_list">
                    <li>
                        <p class="posts">{{ post.title }}</p>
                    </li>
                </ul>
            </div>
        {% endfor %}
        {% if user_threads|length == 0 %}
            <p class="posts" style="text-align: center;">No Threads To Show</p>
        {% endif %} 
        </div>
    {% endif %}

    {% for category, threads in threads_category.items %}
    <div id="category_container">
        <div id="content_title">
            {{ category }}
        </div>
            {% for post in threads %}
            <div id="content_link" onclick="location.href='{{ post.get_absolute_url }}'">
                <ul id="content_list">
                    <li>
                        <p class="posts">{{ post.title }}</p>
                    </li>
                </ul>
            </div>
            {% endfor %}
            {% if threads|length == 0 %}
                <p class="posts" style="text-align: center;">No Threads To Show</p>
            {% endif %} 
    </div>
    {% endfor %}
{% endblock content %}

Django/hobbysite-E-5-main/templates/forum_update.html
{% extends "base.html" %}

{% block title %}Edit Thread Details{% endblock %}

{% block styles %}
    <style>
        * {
            box-sizing: border-box
        }

        h1{
            text-align: center;
            margin-top: 0px;
        }
        
        input[type=text]{
            width: 100%;
            padding: 10px;
            display: inline-block;
            margin-bottom: 10px;
        }
        
        input[type=text]:focus {
            outline: none;
        }
        
        button {
            background-color: #70DCF8;
            color: black;
            font-weight: bold;
            padding: 14px 20px;
            margin: 8px 0;
            border: none;
            cursor: pointer;
            width: 100%;
            opacity: 0.9;
        }
        
        button:hover {
            opacity:1;
        }
        
        .container {
            padding: 30px;
            width: 30%;
            margin-left: auto;
            margin-right: auto;
            margin-top: 60px;
            border: 1px solid black;
            border-radius: 5px;
            box-shadow: 2px 2px #888888;
        }

        #return {
            position: relative;
            top: -60px;
            left: -25px;
            color: black;
            text-decoration: none;
        }

        #return:hover{
            opacity: 0.7;
            transition: opacity 0.3s ease;
        }

        select {
            width: 100%;
        }

        textarea {
            width: 100%;
            resize: none;
        }
    </style>
{% endblock styles %}


{% block content %}
<div class="container">
    <a id="return" href="{% url 'forum:thread' pk=thread.pk %}">Back to Forums</a>
    <h1>Edit Thread</h1>
    {% if is_owner %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button>Submit</button>
        </form>
    {% else %}
        <p style="margin-left: 10px">You are not the owner of this thread</p>
    {% endif %}
</div>

{% endblock content %}

Django/hobbysite-E-5-main/templates/home.html
{% extends "base.html" %}

{% block title %}Homepage{% endblock %}

{% block styles %}
    <style>
        * {
            box-sizing: border-box
        }

        h1{
            text-align: center;
        }
        
        input[type=text], input[type=password], input[type=email] {
            width: 100%;
            padding: 15px;
            display: inline-block;
            border: none;
            background: #f1f1f1;
        }
        
        input[type=text]:focus, input[type=password]:focus {
            background-color: #ddd;
            outline: none;
        }

        .container {
            width: 30%;
            margin-left: auto;
            margin-right: auto;
            margin-top: 35px;
        }
    </style>
{% endblock styles %}

{% block content %}
<div class="container">
    <h1>Home</h1>
    <p style="text-align: justify;"> 
        Introducing Juan Click Wonders: Your tech haven! Dive into a world of limitless possibilities with our wiki, commissions, forums, and merchandise. 
        Get the latest tech insights, bring your ideas to life, connect with fellow enthusiasts, and showcase your tech flair with our products. 
        Explore Juan Click Wonders today and unlock a universe of tech wonders!
    </p>
    {% if user.is_authenticated %}
        <p style="font-size: small; text-align: center;">You are logged in as {{ request.user }}. Click here to <a href="{% url "user_management:logout-user" %}">log out</a></p>
    {% endif %}
</div>

{% endblock content %}

Django/hobbysite-E-5-main/templates/job_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Create Job{% endblock %}

{% block styles %}
    <style>
        a{
            text-decoration: none;
            color:black;
        }
    </style>
{% endblock styles %}

{% block comm %}active{% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button>Submit</button>
</form>
<a href="{% url 'commissions:commission_detail' commission_pk %}">Cancel</a>
{% endblock content %}

Django/hobbysite-E-5-main/templates/wiki.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Wiki{% endblock %}

{% block wiki %}active{% endblock %}

{% block content %}
    <header><img src="{{ article_image.url }}"></header>
    <h2>{{ current_article.title }}</h2>
    <p>Created by: {{ current_article.author.display_name }}</p>
    <p>Category: {{ current_category.get_name_display }}</p>
    <p>Created On: {{ current_article.created_on }}</p>
    <p>Updated On: {{ current_article.updated_on }}</p>
    <p>Entry: {{ current_article.entry }}</p>
    <p>Read More from {{ current_category.get_name_display }} Category</p>
    <ul>
        {% for article in read_others %}
            <li><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>

    {% if request.user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Post Comment">
        </form>
    {% endif %}

    <p>Comments Section</p>
    <ul>
        {% for comment in comments %}
            <li>{{ comment.entry }}</li>
        {% endfor %}
    </ul>

    <p>Want to go back to the Articles List? <a href="{% url "wiki:wiki_list" %}">Click here!</a></p>
    {% if request.user.profile == current_article.author %}
        <p>Want to edit the article? <a href="{% url "wiki:wiki_update" current_article.pk %}">Click here!</a></p>
    {% endif %}
    

    
{% endblock content %}